// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Newtonsoft.Json;

namespace TTFL.ENTITIES
{
    public partial class NbaPlayers
    {
        [JsonProperty("PERSON_ID")]
        public int PersonId { get; set; }
        [JsonProperty("PLAYER_LAST_NAME")]
        public string PlayerLastName { get; set; }
        [JsonProperty("PLAYER_FIRST_NAME")]
        public string PlayerFirstName { get; set; }
        [JsonProperty("TEAM_ID")]
        public int? TeamId { get; set; }
        public string PlayerFullName { get; set; }

        public virtual NbaTeams? NbaTeam { get; set; }
        public virtual ICollection<PickPoints> PickPoints { get; set; }
    }
}