// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TTFL.ENTITIES
{
    public partial class NbaTeams
    {
        public int TeamId { get; set; }
        public string TeamName { get; set; }
        public string Logo { get; set; }
        public string TeamSlug { get; set; }

        public virtual ICollection<NbaPlayers> NbaPlayers { get; set; }
    }
}