// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TTFL.ENTITIES
{
    public partial class PickTeamJson
    {
        public int PickId { get; set; }
        public int TeamId { get; set; }
        public string Json { get; set; }

        public virtual Pick Pick { get; set; }
        public virtual Team Team { get; set; }
    }
}