// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace TTFL.ENTITIES
{
    public partial class PickPoints
    {
        public int PpId { get; set; }
        public int PickId { get; set; }
        public int PlayerId { get; set; }
        public int Rank { get; set; }
        public int Evolution { get; set; }
        public int TotalPoints { get; set; }
        public string PickedPlayer { get; set; }
        public string PickedPlayerName { get; set; }
        public int PickerPlayerPoints { get; set; }
        public bool BestPick { get; set; }
        public int TeamPosition { get; set; }
        public bool HellPick { get; set; }
        public int? NbaPlayerId { get; set; }

        public virtual Pick Pick { get; set; }
        public virtual Player Player { get; set; }
        public virtual NbaPlayers? NbaPlayer { get; set; }
    }
}