// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace TTFL.ENTITIES
{
    public partial class Pick
    {
        public Pick()
        {
            PickPoints = new HashSet<PickPoints>();
            PickTeamJson = new HashSet<PickTeamJson>();
            TeamRank = new HashSet<TeamRank>();
        }

        public int PId { get; set; }
        public int PNumber { get; set; }
        public DateTime PDate { get; set; }
        public bool PIsScrapped { get; set; }

        public virtual ICollection<PickPoints> PickPoints { get; set; }
        public virtual ICollection<PickTeamJson> PickTeamJson { get; set; }
        public virtual ICollection<TeamRank> TeamRank { get; set; }
    }
}