// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TTFL.ENTITIES
{
    public partial class Player
    {
        public Player()
        {
            PickPoints = new HashSet<PickPoints>();
        }

        public int PId { get; set; }
        public string PUsername { get; set; }
        public int? TeamId { get; set; }

        public virtual Team Team { get; set; }
        public virtual ICollection<PickPoints> PickPoints { get; set; }
    }
}