// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace TTFL.ENTITIES
{
    public partial class Statistics
    {
        public int Id { get; set; }
        public string Key { get; set; }
        public string Value { get; set; }
        public string Value2 { get; set; }
        public string Value3 { get; set; }
    }
}