// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TTFL.ENTITIES
{
    public partial class Team
    {
        public Team()
        {
            PickTeamJson = new HashSet<PickTeamJson>();
            Player = new HashSet<Player>();
            TeamRank = new HashSet<TeamRank>();
        }

        public int TId { get; set; }
        public string TName { get; set; }

        public virtual ICollection<PickTeamJson> PickTeamJson { get; set; }
        public virtual ICollection<Player> Player { get; set; }
        public virtual ICollection<TeamRank> TeamRank { get; set; }
    }
}